import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google"; // ganti import font-nya
import "./globals.css";
import { Outfit } from "next/font/google";
import { Sniglet } from "next/font/google";
import { Montserrat } from "next/font/google";

import Header from "./components/Header";
import Footer from "./components/Footer";
import SmoothScroll from "./components/SmoothScroll";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // bebas, sesuai kebutuhan
  display: "swap",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

const sniglet = Sniglet({
  subsets: ["latin"],
  weight: ["400", "800"],
  variable: "--font-sniglet",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // bebas kamu pilih sesuai kebutuhan
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ahmad Akbar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable}  ${outfit.variable} ${montserrat.variable} ${sniglet.variable} font-jakarta`}
      >
        <SmoothScroll />
        <Header />

        <div className="-top-[77px] bg-[#0052FF]">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
