import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
// import { notFound } from "next/navigation";
import { routing } from "@/lib/routing";

import {
  Plus_Jakarta_Sans,
  Outfit,
  Montserrat,
  Sniglet,
} from "next/font/google";
import "../globals.css";
// import Header from "./components/Header";
// import Footer from "./components/Footer";
// import SmoothScroll from "./components/SmoothScroll";
import LayoutClientWrapper from "./LayoutClientWrapper";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });
const sniglet = Sniglet({
  subsets: ["latin"],
  weight: ["400", "800"],
  variable: "--font-sniglet",
  display: "swap",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ahmad Akbar",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

// type Props = {
//   children: React.ReactNode;
//   params: { locale: string };
// };

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages({ locale: params.locale });

  return (
    <html lang={params.locale}>
      <body
        className={`${jakarta.variable} ${outfit.variable} ${montserrat.variable} ${sniglet.variable} font-jakarta`}
      >
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <LayoutClientWrapper>{children}</LayoutClientWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
